version: "3.8"
# link http://localhost:9064/

services:      
  hotels-service:
    image: ghcr.io/vitalii-q/selena-hotels-service/hotels-service:latest
    build: 
      context: ./hotels-service
      dockerfile: Dockerfile
    container_name: hotels-service_${PROJECT_SUFFIX}
    ports:
      - "${SELENA_PORT}:9064"
    depends_on:
      - cockroachdb
      - redis
    env_file:
      - .env
      - ./hotels-service/.env

  users-service:
    image: ghcr.io/vitalii-q/selena-users-service/users-service:latest
    build:
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users-service_${PROJECT_SUFFIX}
    ports:
      - mode: ingress
        target: ${USER_SERVICE_PORT}
        published: ${USER_SERVICE_PORT}
        protocol: tcp
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
      - ./users-service/.env

  bookings-service:
    image: ghcr.io/vitalii-q/selena-bookings-service/bookings-service:latest
    container_name: bookings-service_${PROJECT_SUFFIX}
    build:
      context: ./bookings-service
      dockerfile: Dockerfile
    ports:
      - "9066:9066"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mariadb:9266/bookings
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - mariadb
    command: ["wait-for-mariadb.sh", "db:3306", "--", "java", "-jar", "/app.jar"]

  cockroachdb:
    image: cockroachdb/cockroach:v22.2.7
    container_name: cockroachdb_${PROJECT_SUFFIX}
    command: start-single-node --insecure
    ports:
      - "${DB_PORT}:9264"
    volumes:
    - cockroach_data:/cockroach/cockroach-data

  postgres:
    image: postgres:13
    container_name: postgres_${PROJECT_SUFFIX}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:latest
    container_name: mariadb_${PROJECT_SUFFIX}
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookings
    ports:
      - "${MARIADB_PORT}:9266"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=127.0.0.1", "--user=root", "--password=password"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis_${PROJECT_SUFFIX}
    ports:
      - "${REDIS_PORT}:9764"
    volumes:
      - redis_data:/data

volumes:
  cockroach_data: {}
  redis_data: {}
  postgres_data: {}
  mariadb_data: {}

networks:
  app-network:
    driver: bridge