version: "3.8"
# link http://localhost:9064/

services:      
  hotels-service:
    container_name: hotels-service_${PROJECT_SUFFIX}
    image: ghcr.io/vitalii-q/selena/hotels-service:latest
    build: 
      context: ./hotels-service
      dockerfile: Dockerfile
    ports:
      - "${HOTELS_SERVICE_PORT}:${HOTELS_SERVICE_PORT}"
    depends_on:
      - cockroach-db
      - redis
    env_file:
      - .env
      - ./hotels-service/.env

  users-service:
    container_name: users-service_${PROJECT_SUFFIX}
    image: ghcr.io/vitalii-q/selena/users-service:latest
    restart: always
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    networks:
      - app_network
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
      - ./users-service/.env
    volumes:
      - ./users-service:/app/users-service
      - /app/users-service/bin
      - /app/users-service/tmp
    command: air -c .air.toml  # Запускаем air в контейнере для горячей перезагрузки

  bookings-service:
    container_name: bookings-service_${PROJECT_SUFFIX}
    image: ghcr.io/vitalii-q/selena/bookings-service:latest
    build:
      context: ./bookings-service
      dockerfile: Dockerfile
    ports:
      - "${BOOKINGS_SERVICE_PORT}:${BOOKINGS_SERVICE_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mariadb:9266/bookings
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - maria-db
    command: ["wait-for-mariadb.sh", "db:3306", "--", "java", "-jar", "/app.jar"]

  cockroach-db:
    image: cockroachdb/cockroach:v22.2.7
    container_name: cockroach-db_${PROJECT_SUFFIX}
    command: start-single-node --insecure
    ports:
      - "${COCKROACH_PORT}:${COCKROACH_PORT}"
    volumes:
    - cockroach-data:/cockroach/cockroach-data

  postgres:
    image: postgres:13
    container_name: postgres_${PROJECT_SUFFIX}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  maria-db:
    image: mariadb:10.11
    container_name: maria-db_${PROJECT_SUFFIX}
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookings
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=127.0.0.1", "--user=root", "--password=password"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app_network
    volumes:
    - mariadb-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis_${PROJECT_SUFFIX}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data

  kong-db:
    image: postgres:15
    container_name: kong-db_${PROJECT_SUFFIX}
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
    - app_network
    volumes:
    - kong-db-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:3.9
    container_name: kong-migrations_${PROJECT_SUFFIX}
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db_${PROJECT_SUFFIX}
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_PORT: "5432"
    #command: kong migrations bootstrap
    #command: ["sh", "-c", "kong migrations bootstrap && tail -f /dev/null"]
    networks:
      - app_network
    entrypoint: ["sh", "-c", "kong migrations bootstrap && exit 0"]
    depends_on:
      kong-db:
        condition: service_healthy

  kong:
    image: kong:3.9
    container_name: kong_${PROJECT_SUFFIX}
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db_${PROJECT_SUFFIX}
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PG_PORT: "5432"
      KONG_PORTAL: "true"                     # Включаем портал
      KONG_PORTAL_GUI_HOST: "localhost:8003"   # Адрес для доступа, если доступ из локальной сети
      KONG_PORTAL_API_URI: "http://kong:8001"  # URL API для порта администратора
      KONG_ADMIN_GUI_SSL_CERT: /usr/local/kong/ssl/admin-gui-kong-default.crt   
      KONG_ADMIN_GUI_SSL_CERT_KEY: /usr/local/kong/ssl/admin-gui-kong-default.key
    ports:
      - "8000:8000"   # HTTP-прокси
      - "8443:8443"   # HTTPS-прокси
      - "8001:8001"   # Админ-интерфейс Kong (для взаимодействия с API)
    volumes:
      - ./api-gateway/config/.kong_env:/usr/local/kong/.kong_env
      - ./api-gateway/config:/etc/kong/
      - ./api-gateway/certs/admin-gui-kong-default.crt:/usr/local/kong/ssl/admin-gui-kong-default.crt
      - ./api-gateway/certs/admin-gui-kong-default.key:/usr/local/kong/ssl/admin-gui-kong-default.key
      - ./api-gateway/certs/ffdhe2048.pem:/usr/local/kong/ssl/ffdhe2048.pem
      - ./api-gateway/plugins:/usr/local/kong/plugins/
      - ./wait-for-it.sh:/wait-for-it.sh
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      kong-db:
        condition: service_healthy
      kong-migrations:
        condition: service_completed_successfully
    command: ["kong", "start"]

volumes:
  cockroach-data: {}
  redis-data: {}
  postgres-data: {}
  mariadb-data: {}
  kong-db-data: {}
  kong-data: {}

networks:
  app_network:
    driver: bridge