version: "3.8"
# link http://localhost:9064/

services:      
  hotels-service:
    image: ghcr.io/vitalii-q/selena-hotels-service/hotels-service:latest
    build: 
      context: ./hotels-service
      dockerfile: Dockerfile
    container_name: hotels-service_${PROJECT_SUFFIX}
    ports:
      - "${SELENA_PORT}:9064"
    depends_on:
      - db
      - redis
    env_file:
      - .env
      - ./hotels-service/.env

  db:
    image: cockroachdb/cockroach:v22.2.7
    container_name: cockroachdb_${PROJECT_SUFFIX}
    command: start-single-node --insecure
    ports:
      - "${DB_PORT}:9264"
    volumes:
    - cockroach_data:/cockroach/cockroach-data

  redis:
    image: redis:7
    container_name: redis_${PROJECT_SUFFIX}
    ports:
      - "${REDIS_PORT}:9764"
    volumes:
      - redis_data:/data

  users-service:
    image: ghcr.io/vitalii-q/selena-users-service/users-service:latest
    build:
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users-service_${PROJECT_SUFFIX}
    ports:
      - mode: ingress
        target: ${USER_SERVICE_PORT}
        published: ${USER_SERVICE_PORT}
        protocol: tcp
    depends_on:
      - db
      - redis
    env_file:
      - .env
      - ./users-service/.env

volumes:
  cockroach_data: {}
  redis_data: {}